version: "3"

services:

  postgres:
    image: postgres:14
    container_name: wellplan_postgres
    environment:
      POSTGRES_SERVER: postgres
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    stdin_open: true
    tty: true
    image: wellplan_webapp
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: wellplan_app
    command: /fastapi-start
    env_file: .env
    depends_on:
      - postgres
    ports:
      - 8000:80
    volumes:
      - ./:/app/


volumes:
  pg_data: {}
  